### ISSUE TITLE
Use of Github Discussions

### ISSUE THREAD

**Issue by tsloughter** [open-telemetry/sig-developer-experience#7]
I had the thought that a potential use for Github Discussions may be to have open an initial (as in, we may have a more official and structured user feedback option in the future) area where anyone can open and comment on topics related to their experience with using OpenTelemetry and suggestions for where this could be improved.

What do others think? As of now Discussions are not enabled on this project and I will not enable them unless it is agreed this could be a useful place to collect feedback.

I figure with the Github API these are technically programmatically available, not stuck in Github, and can be retrieved for analysis if needed.

**Comment by julianocosta89** [comment]
My 0.02 cents here is that we must focus on one initial place to collect the feedback from users.
Having the end-users survey + discussions may divide people.

I do like GH Discussions though, but maybe for a later stage of the project.

**Comment by dmathieu** [comment]
Issues can also be converted into discussions rather easily. So, as things grow, we can expand?

**Comment by tedsuo** [comment]
So, a while back we made a decision across OTel to not use discussions, and just stick with issues and project boards. Discussions added one more place for maintainers to monitor, and a lot of what comes in there ends up being duplicate conversations for what is going on in issues.

How about we try sticking with issues for now, and see how it goes?

**Comment by tsloughter** [comment]
Ok. That sounds fine. I wanted to keep issues to internal discussions and have a place for end users, but we may decide on a different place than discussions for that or it end up being no extra wrangling what with labels if they were in issues anyway.
